package com.testfairy.plugin.intellij;

import java.io.*;
import java.util.Scanner;

public class BuildFilePatcher {
	private File fileToPatch;

	public BuildFilePatcher(File androidBuildFile) {
		this.fileToPatch = androidBuildFile;
	}

	public static boolean isTestfairyGradlePluginConfigured(File androidBuildFile) {
		String fileContents;
		try {
			fileContents = new Scanner(androidBuildFile).useDelimiter("\\Z").next();
		} catch (FileNotFoundException e) {
			return false;
		}
		return fileContents.contains("classpath 'com.testfairy.plugins.gradle:testfairy:");
	}

	public void patchBuildFile(String testFairyApiKey) throws IOException {

		String lines[] = Util.readFileLines(fileToPatch);
		StringWriter patched = new StringWriter();
		PrintWriter printWriter = new PrintWriter(patched);
		boolean inPatch = false;
		boolean oldPatchFound = false;
		for (String line : lines) {

			if (line.startsWith("//TestFairy start")) {
				inPatch = true;
				oldPatchFound = true;
				printPatchTo(printWriter, testFairyApiKey);
			}
			if (!inPatch) {
				printWriter.println(line);
			}
			if (line.startsWith("//TestFairy end")) {
				inPatch = false;
			}
		}

		if (oldPatchFound) {
			//rewrite config and testfairy plugin config
			PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(fileToPatch, false)));
			out.print(patched.toString());
			out.close();
		} else {
			//append testfairy config
			PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(fileToPatch, true)));
			out.println();
			printPatchTo(out, testFairyApiKey);
			out.close();
		}
	}

	private void printPatchTo(PrintWriter patched, String testFairyApiKey) {

		patched.println("//TestFairy start - autogenerated by TestFairy intellij plugin");
		patched.println("//manual changes might get overwritten");
		patched.println("buildscript {");
		patched.println("   repositories {");
		patched.println("       mavenCentral()");
		patched.println("       maven { url 'https://www.testfairy.com/maven' }");
		patched.println("   }");
		patched.println("   dependencies {");
		patched.println("       classpath 'com.testfairy.plugins.gradle:testfairy:2.+'");
		patched.println("   }");
		patched.println("}");
		patched.println("apply plugin: 'testfairy'");
		patched.println("android {");
		patched.println("   testfairyConfig {");
		patched.println("       apiKey '" + testFairyApiKey + "'");
		patched.println("   }");
		patched.println("}");
		patched.println("//TestFairy end");
	}
}
