package com.testfairy.plugin.intellij;

import java.io.*;
import java.util.Scanner;

public class BuildFilePatcher {
    private File fileToPatch;

    public BuildFilePatcher(File androidBuildFile) {
        this.fileToPatch = androidBuildFile;
    }

    public static boolean isTestfairyGradlePluginConfigured(File androidBuildFile) {
        String fileContents;
        try {
            fileContents = new Scanner(androidBuildFile).useDelimiter("\\Z").next();
        } catch (FileNotFoundException e) {
            return false;
        }
        return fileContents.contains("autogenerated by TestFairy intellij plugin");
    }

    public void patchBuildFile(TestFairyConfig testFairyConfig) throws IOException {

        String lines[] = Util.readFileLines(fileToPatch);
        StringWriter patched = new StringWriter();
        PrintWriter printWriter = new PrintWriter(patched);
        boolean inPatch = false;
        boolean oldPatchFound = false;
        for (String line : lines) {

            if (line.startsWith("//TestFairy start")) {
                inPatch = true;
                oldPatchFound = true;
                printPatchTo(printWriter, testFairyConfig);
            }
            if (!inPatch) {
                printWriter.println(line);
            }
            if (line.startsWith("//TestFairy end")) {
                inPatch = false;
            }
        }

        if (oldPatchFound) {
            //rewrite config and testfairy plugin config
            PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(fileToPatch, false)));
            out.print(patched.toString());
            out.close();
        } else {
            //append testfairy config
            PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter(fileToPatch, true)));
            out.println();
            printPatchTo(out, testFairyConfig);
            out.close();
        }
    }

    private void printPatchTo(PrintWriter patched, TestFairyConfig testFairyConfig) {
        patched.println("//TestFairy start - autogenerated by TestFairy intellij plugin");
        patched.println("//manual changes might get overwritten");
        patched.println("buildscript {");
        patched.println("   repositories {");
        patched.println("       mavenCentral()");
        patched.println("       maven { url 'https://www.testfairy.com/maven' }");
        patched.println("   }");
        patched.println("   dependencies {");
        patched.println("       classpath 'com.testfairy.plugins.gradle:testfairy:1.+'");
        patched.println("   }");
        patched.println("}");
        patched.println("apply plugin: 'testfairy'");
        patched.println("android {");
        patched.println("   testfairyConfig {");
        patched.println("       apiKey '" + testFairyConfig.getApiKey() + "'");
        patched.println("   }");
        patched.println("}");
        patched.println("//TestFairy end");
    }
}
